apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: prisma-decision-api-public
spec:
  environments:
    - name: public
      build:
        from: public|public-deploy*
    - name: design
      build:
        from: design|design-deploy*
  components:
    - name: api
      src: .
      dockerfileName: api.Dockerfile
      ports:
        - name: http
          port: 7075
      publicPort: http
      resources:
        requests:
          memory: '2000Mi'
          cpu: '200m'
        limits:
          memory: '10000Mi'
          cpu: '1000m'
        horizontalScaling:
          resources:
            memory:
              averageUtilization: 75
            cpu:
              averageUtilization: 85
          minReplicas: 1
          maxReplicas: 3
      environmentConfig:
        - environment: public
          replicas: 1
          variables:
            ASPNETCORE_ENVIRONMENT: 'Public'
          secretRefs:
            azureKeyVaults:
                - name: kvprismadecisionprodsw
                  useAzureIdentity: true
                  items:
                      - name: applicationinsightapiprod
                        envVar: APPINSIGHTS_CONNECTIONSTRING
          identity:
            azure:
                clientId: 23042ef9-dbae-40e9-9345-626087966321
        - environment: design
          replicas: 1
          variables:
            ASPNETCORE_ENVIRONMENT: 'Public'
          secretRefs:
            azureKeyVaults:
                - name: kvprismadecisionprodsw
                  useAzureIdentity: true
                  items:
                      - name: applicationinsightapiprod
                        envVar: APPINSIGHTS_CONNECTIONSTRING
          identity:
            azure:
                clientId: 23042ef9-dbae-40e9-9345-626087966321
        - environment: design
          replicas: 1
          variables:
            ASPNETCORE_ENVIRONMENT: 'Public'
            secretRefs:
            azureKeyVaults:
                - name: kvprismadecisionprodsw
                  useAzureIdentity: true
                  items:
                      - name: applicationinsightapiprod
                        envVar: APPINSIGHTS_CONNECTIONSTRING
          identity:
            azure:
                clientId: 23042ef9-dbae-40e9-9345-626087966321
    - name: fastapi
      src: .
      dockerfileName: fastApi.Dockerfile
      ports:
        - name: http
          port: 8000
      resources:
        requests:
          memory: '2000Mi'
          cpu: '200m'
        limits:
          memory: '10000Mi'
          cpu: '1000m'
        horizontalScaling:
          resources:
            memory:
              averageUtilization: 75
            cpu:
              averageUtilization: 85
          minReplicas: 1
          maxReplicas: 3
      environmentConfig:
        - environment: public
          replicas: 1
