"""add strategies

Revision ID: 226ee6518f24
Revises: 53070751d7f7
Create Date: 2026-01-30 08:12:15.786469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.models.guid import GUID

# revision identifiers, used by Alembic.
revision: str = '226ee6518f24'
down_revision: Union[str, None] = '53070751d7f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('project_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=False),
    sa.Column('rationale', sa.String(length=600), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_strategy_created_by_id_user')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_strategy_project_id_project')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_strategy_updated_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy'))
    )
    op.create_index(op.f('ix_strategy_id'), 'strategy', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_name'), 'strategy', ['name'], unique=False)
    op.create_index(op.f('ix_strategy_project_id'), 'strategy', ['project_id'], unique=False)
    op.create_table('strategy_option',
    sa.Column('strategy_id', GUID(), nullable=False),
    sa.Column('option_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], name=op.f('fk_strategy_option_option_id_option')),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], name=op.f('fk_strategy_option_strategy_id_strategy')),
    sa.PrimaryKeyConstraint('strategy_id', 'option_id', name=op.f('pk_strategy_option'))
    )
    op.create_index(op.f('ix_strategy_option_option_id'), 'strategy_option', ['option_id'], unique=False)
    op.create_index(op.f('ix_strategy_option_strategy_id'), 'strategy_option', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_option_strategy_id'), table_name='strategy_option')
    op.drop_index(op.f('ix_strategy_option_option_id'), table_name='strategy_option')
    op.drop_table('strategy_option')
    op.drop_index(op.f('ix_strategy_project_id'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_name'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_id'), table_name='strategy')
    op.drop_table('strategy')
    # ### end Alembic commands ###
