"""Create a baseline migrations

Revision ID: 3183246ddc64
Revises: 
Create Date: 2026-01-14 14:41:47.731776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.models import guid


# revision identifiers, used by Alembic.
revision: str = '3183246ddc64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('azure_id', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('azure_id', name=op.f('uq_user_azure_id'))
    )
    op.create_table('value_metric',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_value_metric'))
    )
    op.create_table('project',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('parent_project_id', guid.GUID(), nullable=True),
    sa.Column('parent_project_name', sa.String(length=60), nullable=True),
    sa.Column('opportunityStatement', sa.String(length=600), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_project_created_by_id_user')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_project_updated_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_index(op.f('ix_project_parent_project_id'), 'project', ['parent_project_id'], unique=False)
    op.create_table('issue',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('project_id', guid.GUID(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('boundary', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_issue_created_by_id_user')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_issue_project_id_project')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_issue_updated_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue'))
    )
    op.create_index(op.f('ix_issue_name'), 'issue', ['name'], unique=False)
    op.create_index(op.f('ix_issue_project_id'), 'issue', ['project_id'], unique=False)
    op.create_table('objective',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('project_id', guid.GUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_objective_created_by_id_user')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_objective_project_id_project')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_objective_updated_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objective'))
    )
    op.create_index(op.f('ix_objective_name'), 'objective', ['name'], unique=False)
    op.create_index(op.f('ix_objective_project_id'), 'objective', ['project_id'], unique=False)
    op.create_table('opportunity',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('project_id', guid.GUID(), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_opportunity_created_by_id_user')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_opportunity_project_id_project')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_opportunity_updated_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity'))
    )
    op.create_index(op.f('ix_opportunity_project_id'), 'opportunity', ['project_id'], unique=False)
    op.create_table('project_role',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('project_id', guid.GUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_project_role_created_by_id_user')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_role_project_id_project')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_project_role_updated_by_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_project_role_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_role'))
    )
    op.create_index(op.f('ix_project_role_project_id'), 'project_role', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_role_user_id'), 'project_role', ['user_id'], unique=False)
    op.create_table('decision',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('issue_id', guid.GUID(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], name=op.f('fk_decision_issue_id_issue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision'))
    )
    op.create_index(op.f('ix_decision_issue_id'), 'decision', ['issue_id'], unique=False)
    op.create_table('node',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('project_id', guid.GUID(), nullable=False),
    sa.Column('issue_id', guid.GUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], name=op.f('fk_node_issue_id_issue')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_node_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node'))
    )
    op.create_index(op.f('ix_node_issue_id'), 'node', ['issue_id'], unique=False)
    op.create_index(op.f('ix_node_name'), 'node', ['name'], unique=False)
    op.create_index(op.f('ix_node_project_id'), 'node', ['project_id'], unique=False)
    op.create_table('uncertainty',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('issue_id', guid.GUID(), nullable=False),
    sa.Column('is_key', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], name=op.f('fk_uncertainty_issue_id_issue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uncertainty'))
    )
    op.create_index(op.f('ix_uncertainty_issue_id'), 'uncertainty', ['issue_id'], unique=False)
    op.create_table('utility',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('issue_id', guid.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issue.id'], name=op.f('fk_utility_issue_id_issue')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_utility'))
    )
    op.create_index(op.f('ix_utility_issue_id'), 'utility', ['issue_id'], unique=False)
    op.create_table('discrete_utility',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('value_metric_id', guid.GUID(), nullable=False),
    sa.Column('utility_id', guid.GUID(), nullable=False),
    sa.Column('utility_value', sa.Float(precision=53), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utility_id'], ['utility.id'], name=op.f('fk_discrete_utility_utility_id_utility')),
    sa.ForeignKeyConstraint(['value_metric_id'], ['value_metric.id'], name=op.f('fk_discrete_utility_value_metric_id_value_metric'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discrete_utility'))
    )
    op.create_index(op.f('ix_discrete_utility_utility_id'), 'discrete_utility', ['utility_id'], unique=False)
    op.create_index(op.f('ix_discrete_utility_value_metric_id'), 'discrete_utility', ['value_metric_id'], unique=False)
    op.create_table('edge',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('tail_id', guid.GUID(), nullable=False),
    sa.Column('head_id', guid.GUID(), nullable=False),
    sa.Column('project_id', guid.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['head_id'], ['node.id'], name=op.f('fk_edge_head_id_node')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_edge_project_id_project')),
    sa.ForeignKeyConstraint(['tail_id'], ['node.id'], name=op.f('fk_edge_tail_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_edge'))
    )
    op.create_index(op.f('ix_edge_head_id'), 'edge', ['head_id'], unique=False)
    op.create_index(op.f('ix_edge_project_id'), 'edge', ['project_id'], unique=False)
    op.create_index(op.f('ix_edge_tail_id'), 'edge', ['tail_id'], unique=False)
    op.create_table('node_style',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('node_id', guid.GUID(), nullable=False),
    sa.Column('x_position', sa.Float(precision=53), nullable=False),
    sa.Column('y_position', sa.Float(precision=53), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], name=op.f('fk_node_style_node_id_node')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_style'))
    )
    op.create_index(op.f('ix_node_style_node_id'), 'node_style', ['node_id'], unique=False)
    op.create_table('option',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('decision_id', guid.GUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('utility', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision.id'], name=op.f('fk_option_decision_id_decision')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_option'))
    )
    op.create_index(op.f('ix_option_decision_id'), 'option', ['decision_id'], unique=False)
    op.create_table('outcome',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('uncertainty_id', guid.GUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('utility', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uncertainty_id'], ['uncertainty.id'], name=op.f('fk_outcome_uncertainty_id_uncertainty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcome'))
    )
    op.create_index(op.f('ix_outcome_uncertainty_id'), 'outcome', ['uncertainty_id'], unique=False)
    op.create_table('discrete_probability',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('outcome_id', guid.GUID(), nullable=False),
    sa.Column('uncertainty_id', guid.GUID(), nullable=False),
    sa.Column('probability', sa.Float(precision=53), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], name=op.f('fk_discrete_probability_outcome_id_outcome'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uncertainty_id'], ['uncertainty.id'], name=op.f('fk_discrete_probability_uncertainty_id_uncertainty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discrete_probability'))
    )
    op.create_index(op.f('ix_discrete_probability_outcome_id'), 'discrete_probability', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_discrete_probability_uncertainty_id'), 'discrete_probability', ['uncertainty_id'], unique=False)
    op.create_table('discrete_utility_parent_option',
    sa.Column('discrete_utility_id', guid.GUID(), nullable=False),
    sa.Column('parent_option_id', guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['discrete_utility_id'], ['discrete_utility.id'], name=op.f('fk_discrete_utility_parent_option_discrete_utility_id_discrete_utility')),
    sa.ForeignKeyConstraint(['parent_option_id'], ['option.id'], name=op.f('fk_discrete_utility_parent_option_parent_option_id_option'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discrete_utility_id', 'parent_option_id', name=op.f('pk_discrete_utility_parent_option'))
    )
    op.create_table('discrete_utility_parent_outcome',
    sa.Column('discrete_utility_id', guid.GUID(), nullable=False),
    sa.Column('parent_outcome_id', guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['discrete_utility_id'], ['discrete_utility.id'], name=op.f('fk_discrete_utility_parent_outcome_discrete_utility_id_discrete_utility')),
    sa.ForeignKeyConstraint(['parent_outcome_id'], ['outcome.id'], name=op.f('fk_discrete_utility_parent_outcome_parent_outcome_id_outcome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discrete_utility_id', 'parent_outcome_id', name=op.f('pk_discrete_utility_parent_outcome'))
    )
    op.create_table('discrete_probability_parent_option',
    sa.Column('discrete_probability_id', guid.GUID(), nullable=False),
    sa.Column('parent_option_id', guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['discrete_probability_id'], ['discrete_probability.id'], name=op.f('fk_discrete_probability_parent_option_discrete_probability_id_discrete_probability')),
    sa.ForeignKeyConstraint(['parent_option_id'], ['option.id'], name=op.f('fk_discrete_probability_parent_option_parent_option_id_option'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discrete_probability_id', 'parent_option_id', name=op.f('pk_discrete_probability_parent_option'))
    )
    op.create_table('discrete_probability_parent_outcome',
    sa.Column('discrete_probability_id', guid.GUID(), nullable=False),
    sa.Column('parent_outcome_id', guid.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['discrete_probability_id'], ['discrete_probability.id'], name=op.f('fk_discrete_probability_parent_outcome_discrete_probability_id_discrete_probability')),
    sa.ForeignKeyConstraint(['parent_outcome_id'], ['outcome.id'], name=op.f('fk_discrete_probability_parent_outcome_parent_outcome_id_outcome'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discrete_probability_id', 'parent_outcome_id', name=op.f('pk_discrete_probability_parent_outcome'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discrete_probability_parent_outcome')
    op.drop_table('discrete_probability_parent_option')
    op.drop_table('discrete_utility_parent_outcome')
    op.drop_table('discrete_utility_parent_option')
    op.drop_index(op.f('ix_discrete_probability_uncertainty_id'), table_name='discrete_probability')
    op.drop_index(op.f('ix_discrete_probability_outcome_id'), table_name='discrete_probability')
    op.drop_table('discrete_probability')
    op.drop_index(op.f('ix_outcome_uncertainty_id'), table_name='outcome')
    op.drop_table('outcome')
    op.drop_index(op.f('ix_option_decision_id'), table_name='option')
    op.drop_table('option')
    op.drop_index(op.f('ix_node_style_node_id'), table_name='node_style')
    op.drop_table('node_style')
    op.drop_index(op.f('ix_edge_tail_id'), table_name='edge')
    op.drop_index(op.f('ix_edge_project_id'), table_name='edge')
    op.drop_index(op.f('ix_edge_head_id'), table_name='edge')
    op.drop_table('edge')
    op.drop_index(op.f('ix_discrete_utility_value_metric_id'), table_name='discrete_utility')
    op.drop_index(op.f('ix_discrete_utility_utility_id'), table_name='discrete_utility')
    op.drop_table('discrete_utility')
    op.drop_index(op.f('ix_utility_issue_id'), table_name='utility')
    op.drop_table('utility')
    op.drop_index(op.f('ix_uncertainty_issue_id'), table_name='uncertainty')
    op.drop_table('uncertainty')
    op.drop_index(op.f('ix_node_project_id'), table_name='node')
    op.drop_index(op.f('ix_node_name'), table_name='node')
    op.drop_index(op.f('ix_node_issue_id'), table_name='node')
    op.drop_table('node')
    op.drop_index(op.f('ix_decision_issue_id'), table_name='decision')
    op.drop_table('decision')
    op.drop_index(op.f('ix_project_role_user_id'), table_name='project_role')
    op.drop_index(op.f('ix_project_role_project_id'), table_name='project_role')
    op.drop_table('project_role')
    op.drop_index(op.f('ix_opportunity_project_id'), table_name='opportunity')
    op.drop_table('opportunity')
    op.drop_index(op.f('ix_objective_project_id'), table_name='objective')
    op.drop_index(op.f('ix_objective_name'), table_name='objective')
    op.drop_table('objective')
    op.drop_index(op.f('ix_issue_project_id'), table_name='issue')
    op.drop_index(op.f('ix_issue_name'), table_name='issue')
    op.drop_table('issue')
    op.drop_index(op.f('ix_project_parent_project_id'), table_name='project')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_table('project')
    op.drop_table('value_metric')
    op.drop_table('user')
    # ### end Alembic commands ###
