"""Remove opportunities

Revision ID: 3631746248c3
Revises: 3183246ddc64
Create Date: 2026-01-16 15:38:36.691312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '3631746248c3'
down_revision: Union[str, None] = '3183246ddc64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_project_id'), table_name='opportunity')
    op.drop_table('opportunity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('project_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('created_at', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_opportunity_created_by_id_user')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_opportunity_project_id_project')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_opportunity_updated_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity'))
    )
    op.create_index(op.f('ix_opportunity_project_id'), 'opportunity', ['project_id'], unique=False)
    # ### end Alembic commands ###
