"""convert number type

Revision ID: 496ba59b23c7
Revises: ec2aad9de30f
Create Date: 2025-12-08 14:56:57.285143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '496ba59b23c7'
down_revision: Union[str, None] = 'ec2aad9de30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discrete_probability', 'probability',
               existing_type=mssql.REAL(),
               type_=sa.Float(precision=53),
               existing_nullable=True)
    op.alter_column('node_style', 'x_position',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=53),
               existing_nullable=False)
    op.alter_column('node_style', 'y_position',
               existing_type=mssql.REAL(),
               type_=sa.FLOAT(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node_style', 'y_position',
               existing_type=sa.FLOAT(precision=53),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.alter_column('node_style', 'x_position',
               existing_type=sa.FLOAT(precision=53),
               type_=mssql.REAL(),
               existing_nullable=False)
    op.alter_column('discrete_probability', 'probability',
               existing_type=sa.Float(precision=53),
               type_=mssql.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
