"""add_cascade_delete_to_decision_uncertainty_utility_fk

Revision ID: 53070751d7f7
Revises: 1eec0879728f
Create Date: 2026-01-28 13:54:25.644711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53070751d7f7'
down_revision: Union[str, None] = '1eec0879728f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_decision_issue_id_issue'), 'decision', type_='foreignkey')
    op.create_foreign_key(op.f('fk_decision_issue_id_issue'), 'decision', 'issue', ['issue_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_uncertainty_issue_id_issue'), 'uncertainty', type_='foreignkey')
    op.create_foreign_key(op.f('fk_uncertainty_issue_id_issue'), 'uncertainty', 'issue', ['issue_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_utility_issue_id_issue'), 'utility', type_='foreignkey')
    op.create_foreign_key(op.f('fk_utility_issue_id_issue'), 'utility', 'issue', ['issue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_utility_issue_id_issue'), 'utility', type_='foreignkey')
    op.create_foreign_key(op.f('fk_utility_issue_id_issue'), 'utility', 'issue', ['issue_id'], ['id'])
    op.drop_constraint(op.f('fk_uncertainty_issue_id_issue'), 'uncertainty', type_='foreignkey')
    op.create_foreign_key(op.f('fk_uncertainty_issue_id_issue'), 'uncertainty', 'issue', ['issue_id'], ['id'])
    op.drop_constraint(op.f('fk_decision_issue_id_issue'), 'decision', type_='foreignkey')
    op.create_foreign_key(op.f('fk_decision_issue_id_issue'), 'decision', 'issue', ['issue_id'], ['id'])
    # ### end Alembic commands ###
