"""utilities

Revision ID: 5b575ab7caca
Revises: 496ba59b23c7
Create Date: 2025-12-10 07:22:47.959588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

from src.models.guid import GUID

# revision identifiers, used by Alembic.
revision: str = '5b575ab7caca'
down_revision: Union[str, None] = '496ba59b23c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discrete_utility',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('value_metric_id', GUID(), nullable=False),
    sa.Column('utility_id', GUID(), nullable=False),
    sa.Column('utility_value', sa.Float(precision=53), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utility_id'], ['utility.id'], ),
    sa.ForeignKeyConstraint(['value_metric_id'], ['value_metric.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discrete_utility_utility_id'), 'discrete_utility', ['utility_id'], unique=False)
    op.create_index(op.f('ix_discrete_utility_value_metric_id'), 'discrete_utility', ['value_metric_id'], unique=False)
    op.create_table('discrete_utility_parent_option',
    sa.Column('discrete_utility_id', GUID(), nullable=False),
    sa.Column('parent_option_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['discrete_utility_id'], ['discrete_utility.id'], ),
    sa.ForeignKeyConstraint(['parent_option_id'], ['option.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discrete_utility_id', 'parent_option_id')
    )
    op.create_table('discrete_utility_parent_outcome',
    sa.Column('discrete_utility_id', GUID(), nullable=False),
    sa.Column('parent_outcome_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['discrete_utility_id'], ['discrete_utility.id'], ),
    sa.ForeignKeyConstraint(['parent_outcome_id'], ['outcome.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discrete_utility_id', 'parent_outcome_id')
    )
    op.drop_column('utility', 'values')
    op.drop_constraint(op.f('FK__value_met__issue__4959E263'), 'value_metric', type_='foreignkey')
    op.drop_index(op.f('ix_value_metric_issue_id'), table_name='value_metric')
    op.drop_column('value_metric', 'issue_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('value_metric', sa.Column('issue_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('FK__value_met__issue__4959E263'), 'value_metric', 'issue', ['issue_id'], ['id'])
    op.create_index(op.f('ix_value_metric_issue_id'), 'value_metric', ['issue_id'], unique=False)
    op.add_column('utility', sa.Column('values', sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.drop_table('discrete_utility_parent_outcome')
    op.drop_table('discrete_utility_parent_option')
    op.drop_index(op.f('ix_discrete_utility_value_metric_id'), table_name='discrete_utility')
    op.drop_index(op.f('ix_discrete_utility_utility_id'), table_name='discrete_utility')
    op.drop_table('discrete_utility')
    # ### end Alembic commands ###
