"""renamed to opportunity_statement

Revision ID: 7856002070ad
Revises: 226ee6518f24
Create Date: 2026-02-11 12:55:14.011949

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7856002070ad'
down_revision: Union[str, None] = '226ee6518f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'opportunityStatement', nullable=False, new_column_name='opportunity_statement')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'opportunity_statement', nullable=False, new_column_name='opportunityStatement')
    # ### end Alembic commands ###
