"""added parent project name

Revision ID: a4893b48c6a1
Revises: 445d0f5cdb10
Create Date: 2025-12-18 12:34:01.586303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4893b48c6a1'
down_revision: Union[str, None] = '445d0f5cdb10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('parent_project_name', sa.String(length=60), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'parent_project_name')
