"""parent_project_to_null

Revision ID: f583a4b13594
Revises: a4893b48c6a1
Create Date: 2026-01-06 15:29:43.304094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f583a4b13594'
down_revision: Union[str, None] = 'a4893b48c6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'parent_project_name',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("('')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'parent_project_name',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("('')"))
    # ### end Alembic commands ###
