"""add icon color

Revision ID: 60dcdcbca0c3
Revises: c9bb4a8bd3c2
Create Date: 2026-02-26 14:18:23.256564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60dcdcbca0c3'
down_revision: Union[str, None] = 'c9bb4a8bd3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('icon_color', sa.String(length=600), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_id'), table_name='strategy')
    # ### end Alembic commands ###
