"""Increase max string length

Revision ID: 75a95ac49812
Revises: 60dcdcbca0c3
Create Date: 2026-03-04 14:31:55.104605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a95ac49812'
down_revision: Union[str, None] = '60dcdcbca0c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decision', 'type',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000,collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('issue', 'type',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000,collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('issue', 'boundary',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000,collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('issue', 'name',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000,collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('issue', 'description',
               existing_type=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False) 
    op.alter_column('node', 'name',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('objective', 'name',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('objective', 'type',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('objective', 'description',
               existing_type=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('option', 'name',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('outcome', 'name',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('project', 'parent_project_name',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('project', 'opportunity_statement',
               existing_type=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('project_role', 'role',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('strategy', 'name',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('strategy', 'description',
               existing_type=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('strategy', 'rationale',
               existing_type=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('strategy', 'icon',
               existing_type=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('strategy', 'icon_color',
               existing_type=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.create_index(op.f('ix_strategy_id'), 'strategy', ['id'], unique=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('user', 'azure_id',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'azure_id',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.drop_index(op.f('ix_strategy_id'), table_name='strategy')
    op.alter_column('strategy', 'icon_color',
               existing_type=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('strategy', 'icon',
               existing_type=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('strategy', 'rationale',
               existing_type=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('strategy', 'description',
               existing_type=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('strategy', 'name',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('project_role', 'role',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('project', 'opportunity_statement',
               existing_type=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('project', 'parent_project_name',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('outcome', 'name',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('option', 'name',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('objective', 'description',
               existing_type=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('objective', 'type',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('objective', 'name',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('node', 'name',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('issue', 'description',
               existing_type=sa.VARCHAR(length=6000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=600, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('issue', 'name',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('issue', 'boundary',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('issue', 'type',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    op.alter_column('decision', 'type',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
    # ### end Alembic commands ###
