"""add icon field

Revision ID: c9bb4a8bd3c2
Revises: 7856002070ad
Create Date: 2026-02-26 09:50:08.533793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9bb4a8bd3c2'
down_revision: Union[str, None] = '7856002070ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy', sa.Column('icon', sa.String(length=600), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategy', 'icon')
    # ### end Alembic commands ###
