// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrismaApi.Infrastructure.Context;

#nullable disable

namespace PrismaApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410085059_AddAssessmentAndDQAssessment")]
    partial class AddAssessmentAndDQAssessment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrismaApi.Domain.Entities.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAssessmentCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_assessment_completed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Assessments", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.ToTable("Decisions");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DecisionQualityAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AppropriateFrame")
                        .HasColumnType("int")
                        .HasColumnName("appropriate_frame");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assessment_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int>("CommitmentToAction")
                        .HasColumnType("int")
                        .HasColumnName("commitment_to_action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DoableAlternatives")
                        .HasColumnType("int")
                        .HasColumnName("doable_alternatives");

                    b.Property<int>("InformationReliability")
                        .HasColumnType("int")
                        .HasColumnName("information_reliability");

                    b.Property<int>("ReasoningCorrectness")
                        .HasColumnType("int")
                        .HasColumnName("reasoning_correctness");

                    b.Property<int>("TradeOffAnalysis")
                        .HasColumnType("int")
                        .HasColumnName("trade_off_analysis");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("DecisionQualityAssessments", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Probability")
                        .HasPrecision(53)
                        .HasColumnType("float(53)");

                    b.Property<Guid>("UncertaintyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OutcomeId");

                    b.HasIndex("UncertaintyId");

                    b.ToTable("DiscreteProbabilities");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbabilityParentOption", b =>
                {
                    b.Property<Guid>("DiscreteProbabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiscreteProbabilityId", "ParentOptionId");

                    b.HasIndex("ParentOptionId");

                    b.ToTable("DiscreteProbabilityParentOptions");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbabilityParentOutcome", b =>
                {
                    b.Property<Guid>("DiscreteProbabilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiscreteProbabilityId", "ParentOutcomeId");

                    b.HasIndex("ParentOutcomeId");

                    b.ToTable("DiscreteProbabilityParentOutcomes");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UtilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("UtilityValue")
                        .HasPrecision(53)
                        .HasColumnType("float(53)");

                    b.Property<Guid>("ValueMetricId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilityId");

                    b.HasIndex("ValueMetricId");

                    b.ToTable("DiscreteUtilities");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtilityParentOption", b =>
                {
                    b.Property<Guid>("DiscreteUtilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiscreteUtilityId", "ParentOptionId");

                    b.HasIndex("ParentOptionId");

                    b.ToTable("DiscreteUtilityParentOptions");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtilityParentOutcome", b =>
                {
                    b.Property<Guid>("DiscreteUtilityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiscreteUtilityId", "ParentOutcomeId");

                    b.HasIndex("ParentOutcomeId");

                    b.ToTable("DiscreteUtilityParentOutcomes");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Edge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("HeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("HeadId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TailId");

                    b.ToTable("Edges");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Boundary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.NodeStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("XPosition")
                        .HasColumnType("float");

                    b.Property<double>("YPosition")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("NodeStyles");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Utility")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Outcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("UncertaintyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Utility")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UncertaintyId");

                    b.ToTable("Outcomes");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OpportunityStatement")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParentProjectName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Public")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.ProjectRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectRoles");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Strategies");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.StrategyOption", b =>
                {
                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StrategyId", "OptionId");

                    b.HasIndex("OptionId");

                    b.ToTable("StrategyOptions");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Uncertainty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsKey")
                        .HasColumnType("bit");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.ToTable("Uncertainties");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Utility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.ToTable("Utilities");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.ValueMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ValueMetrics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("288e0811-7ab6-5d24-b80c-9fa925b848a6"),
                            CreatedAt = new DateTimeOffset(new DateTime(2020, 1, 1, 1, 1, 1, 1, DateTimeKind.Unspecified).AddTicks(1), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "value",
                            UpdatedAt = new DateTimeOffset(new DateTime(2020, 1, 1, 1, 1, 1, 1, DateTimeKind.Unspecified).AddTicks(2), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Assessment", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Project", "Project")
                        .WithMany("Assessments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Decision", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Issue", "Issue")
                        .WithOne("Decision")
                        .HasForeignKey("PrismaApi.Domain.Entities.Decision", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DecisionQualityAssessment", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Assessment", "Assessment")
                        .WithMany("DecisionQualityAssessments")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbability", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Outcome", "Outcome")
                        .WithMany()
                        .HasForeignKey("OutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Uncertainty", "Uncertainty")
                        .WithMany("DiscreteProbabilities")
                        .HasForeignKey("UncertaintyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Outcome");

                    b.Navigation("Uncertainty");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbabilityParentOption", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.DiscreteProbability", "DiscreteProbability")
                        .WithMany("ParentOptions")
                        .HasForeignKey("DiscreteProbabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Option", "ParentOption")
                        .WithMany()
                        .HasForeignKey("ParentOptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DiscreteProbability");

                    b.Navigation("ParentOption");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbabilityParentOutcome", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.DiscreteProbability", "DiscreteProbability")
                        .WithMany("ParentOutcomes")
                        .HasForeignKey("DiscreteProbabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Outcome", "ParentOutcome")
                        .WithMany()
                        .HasForeignKey("ParentOutcomeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DiscreteProbability");

                    b.Navigation("ParentOutcome");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtility", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Utility", "Utility")
                        .WithMany("DiscreteUtilities")
                        .HasForeignKey("UtilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.ValueMetric", "ValueMetric")
                        .WithMany()
                        .HasForeignKey("ValueMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utility");

                    b.Navigation("ValueMetric");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtilityParentOption", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.DiscreteUtility", "DiscreteUtility")
                        .WithMany("ParentOptions")
                        .HasForeignKey("DiscreteUtilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Option", "ParentOption")
                        .WithMany()
                        .HasForeignKey("ParentOptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DiscreteUtility");

                    b.Navigation("ParentOption");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtilityParentOutcome", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.DiscreteUtility", "DiscreteUtility")
                        .WithMany("ParentOutcomes")
                        .HasForeignKey("DiscreteUtilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Outcome", "ParentOutcome")
                        .WithMany()
                        .HasForeignKey("ParentOutcomeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DiscreteUtility");

                    b.Navigation("ParentOutcome");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Edge", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Node", "HeadNode")
                        .WithMany("HeadEdges")
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Project", "Project")
                        .WithMany("Edges")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Node", "TailNode")
                        .WithMany("TailEdges")
                        .HasForeignKey("TailId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HeadNode");

                    b.Navigation("Project");

                    b.Navigation("TailNode");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Issue", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Project", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Node", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Issue", "Issue")
                        .WithOne("Node")
                        .HasForeignKey("PrismaApi.Domain.Entities.Node", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Project", "Project")
                        .WithMany("Nodes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.NodeStyle", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Node", "Node")
                        .WithOne("NodeStyle")
                        .HasForeignKey("PrismaApi.Domain.Entities.NodeStyle", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Objective", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Project", "Project")
                        .WithMany("Objectives")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Option", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Decision", "Decision")
                        .WithMany("Options")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decision");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Outcome", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Uncertainty", "Uncertainty")
                        .WithMany("Outcomes")
                        .HasForeignKey("UncertaintyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uncertainty");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Project", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.ProjectRole", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Project", "Project")
                        .WithMany("ProjectRoles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "User")
                        .WithMany("ProjectRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Strategy", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Project", "Project")
                        .WithMany("Strategies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.StrategyOption", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Option", "Option")
                        .WithMany("StrategyOptions")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Strategy", "Strategy")
                        .WithMany("StrategyOptions")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Uncertainty", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Issue", "Issue")
                        .WithOne("Uncertainty")
                        .HasForeignKey("PrismaApi.Domain.Entities.Uncertainty", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Utility", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Issue", "Issue")
                        .WithOne("Utility")
                        .HasForeignKey("PrismaApi.Domain.Entities.Utility", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Assessment", b =>
                {
                    b.Navigation("DecisionQualityAssessments");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Decision", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbability", b =>
                {
                    b.Navigation("ParentOptions");

                    b.Navigation("ParentOutcomes");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtility", b =>
                {
                    b.Navigation("ParentOptions");

                    b.Navigation("ParentOutcomes");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Issue", b =>
                {
                    b.Navigation("Decision");

                    b.Navigation("Node");

                    b.Navigation("Uncertainty");

                    b.Navigation("Utility");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Node", b =>
                {
                    b.Navigation("HeadEdges");

                    b.Navigation("NodeStyle");

                    b.Navigation("TailEdges");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Option", b =>
                {
                    b.Navigation("StrategyOptions");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Project", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Edges");

                    b.Navigation("Issues");

                    b.Navigation("Nodes");

                    b.Navigation("Objectives");

                    b.Navigation("ProjectRoles");

                    b.Navigation("Strategies");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Strategy", b =>
                {
                    b.Navigation("StrategyOptions");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Uncertainty", b =>
                {
                    b.Navigation("DiscreteProbabilities");

                    b.Navigation("Outcomes");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.User", b =>
                {
                    b.Navigation("ProjectRoles");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Utility", b =>
                {
                    b.Navigation("DiscreteUtilities");
                });
#pragma warning restore 612, 618
        }
    }
}
