// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrismaApi.Infrastructure;

#nullable disable

namespace PrismaApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313114232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrismaApi.Domain.Entities.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("issue_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.ToTable("decision", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OutcomeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("outcome_id");

                    b.Property<double?>("Probability")
                        .HasPrecision(53)
                        .HasColumnType("float(53)")
                        .HasColumnName("probability");

                    b.Property<Guid>("UncertaintyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uncertainty_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OutcomeId");

                    b.HasIndex("UncertaintyId");

                    b.ToTable("discrete_probability", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbabilityParentOption", b =>
                {
                    b.Property<Guid>("DiscreteProbabilityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("discrete_probability_id");

                    b.Property<Guid>("ParentOptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_option_id");

                    b.HasKey("DiscreteProbabilityId", "ParentOptionId");

                    b.HasIndex("ParentOptionId");

                    b.ToTable("discrete_probability_parent_option", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbabilityParentOutcome", b =>
                {
                    b.Property<Guid>("DiscreteProbabilityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("discrete_probability_id");

                    b.Property<Guid>("ParentOutcomeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_outcome_id");

                    b.HasKey("DiscreteProbabilityId", "ParentOutcomeId");

                    b.HasIndex("ParentOutcomeId");

                    b.ToTable("discrete_probability_parent_outcome", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UtilityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("utility_id");

                    b.Property<double?>("UtilityValue")
                        .HasPrecision(53)
                        .HasColumnType("float(53)")
                        .HasColumnName("utility_value");

                    b.Property<Guid>("ValueMetricId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("value_metric_id");

                    b.HasKey("Id");

                    b.HasIndex("UtilityId");

                    b.HasIndex("ValueMetricId");

                    b.ToTable("discrete_utility", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtilityParentOption", b =>
                {
                    b.Property<Guid>("DiscreteUtilityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("discrete_utility_id");

                    b.Property<Guid>("ParentOptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_option_id");

                    b.HasKey("DiscreteUtilityId", "ParentOptionId");

                    b.HasIndex("ParentOptionId");

                    b.ToTable("discrete_utility_parent_option", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtilityParentOutcome", b =>
                {
                    b.Property<Guid>("DiscreteUtilityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("discrete_utility_id");

                    b.Property<Guid>("ParentOutcomeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_outcome_id");

                    b.HasKey("DiscreteUtilityId", "ParentOutcomeId");

                    b.HasIndex("ParentOutcomeId");

                    b.ToTable("discrete_utility_parent_outcome", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Edge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HeadId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("head_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TailId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tail_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("HeadId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TailId");

                    b.ToTable("edge", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Boundary")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("boundary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("issue", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("issue_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.ToTable("node", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.NodeStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("node_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<double>("XPosition")
                        .HasColumnType("float")
                        .HasColumnName("x_position");

                    b.Property<double>("YPosition")
                        .HasColumnType("float")
                        .HasColumnName("y_position");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("node_style", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("objective", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("decision_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<double>("Utility")
                        .HasColumnType("float")
                        .HasColumnName("utility");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.ToTable("option", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Outcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("name");

                    b.Property<Guid>("UncertaintyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uncertainty_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<double>("Utility")
                        .HasColumnType("float")
                        .HasColumnName("utility");

                    b.HasKey("Id");

                    b.HasIndex("UncertaintyId");

                    b.ToTable("outcome", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("name");

                    b.Property<string>("OpportunityStatement")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)")
                        .HasColumnName("opportunity_statement");

                    b.Property<Guid?>("ParentProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_project_id");

                    b.Property<string>("ParentProjectName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("parent_project_name");

                    b.Property<bool>("Public")
                        .HasColumnType("bit")
                        .HasColumnName("public");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.ProjectRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("project_role", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Strategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("icon");

                    b.Property<string>("IconColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("icon_color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("project_id");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)")
                        .HasColumnName("rationale");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("strategy", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.StrategyOption", b =>
                {
                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("strategy_id");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("option_id");

                    b.HasKey("StrategyId", "OptionId");

                    b.HasIndex("OptionId");

                    b.ToTable("strategy_option", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Uncertainty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsKey")
                        .HasColumnType("bit")
                        .HasColumnName("is_key");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("issue_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.ToTable("uncertainty", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("azure_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AzureId")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Utility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("issue_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IssueId")
                        .IsUnique();

                    b.ToTable("utility", (string)null);
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.ValueMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("value_metric", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("288e0811-7ab6-5d24-b80c-9fa925b848a6"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 13, 11, 42, 32, 191, DateTimeKind.Unspecified).AddTicks(1090), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "value",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 13, 11, 42, 32, 191, DateTimeKind.Unspecified).AddTicks(1090), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Decision", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Issue", "Issue")
                        .WithOne("Decision")
                        .HasForeignKey("PrismaApi.Domain.Entities.Decision", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbability", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Outcome", "Outcome")
                        .WithMany()
                        .HasForeignKey("OutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Uncertainty", "Uncertainty")
                        .WithMany("DiscreteProbabilities")
                        .HasForeignKey("UncertaintyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outcome");

                    b.Navigation("Uncertainty");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbabilityParentOption", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.DiscreteProbability", "DiscreteProbability")
                        .WithMany("ParentOptions")
                        .HasForeignKey("DiscreteProbabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Option", "ParentOption")
                        .WithMany()
                        .HasForeignKey("ParentOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscreteProbability");

                    b.Navigation("ParentOption");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbabilityParentOutcome", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.DiscreteProbability", "DiscreteProbability")
                        .WithMany("ParentOutcomes")
                        .HasForeignKey("DiscreteProbabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Outcome", "ParentOutcome")
                        .WithMany()
                        .HasForeignKey("ParentOutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscreteProbability");

                    b.Navigation("ParentOutcome");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtility", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Utility", "Utility")
                        .WithMany("DiscreteUtilities")
                        .HasForeignKey("UtilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.ValueMetric", "ValueMetric")
                        .WithMany()
                        .HasForeignKey("ValueMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utility");

                    b.Navigation("ValueMetric");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtilityParentOption", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.DiscreteUtility", "DiscreteUtility")
                        .WithMany("ParentOptions")
                        .HasForeignKey("DiscreteUtilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Option", "ParentOption")
                        .WithMany()
                        .HasForeignKey("ParentOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscreteUtility");

                    b.Navigation("ParentOption");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtilityParentOutcome", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.DiscreteUtility", "DiscreteUtility")
                        .WithMany("ParentOutcomes")
                        .HasForeignKey("DiscreteUtilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Outcome", "ParentOutcome")
                        .WithMany()
                        .HasForeignKey("ParentOutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscreteUtility");

                    b.Navigation("ParentOutcome");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Edge", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Node", "HeadNode")
                        .WithMany("HeadEdges")
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Project", "Project")
                        .WithMany("Edges")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Node", "TailNode")
                        .WithMany("TailEdges")
                        .HasForeignKey("TailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeadNode");

                    b.Navigation("Project");

                    b.Navigation("TailNode");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Issue", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Project", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Node", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Issue", "Issue")
                        .WithOne("Node")
                        .HasForeignKey("PrismaApi.Domain.Entities.Node", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Project", "Project")
                        .WithMany("Nodes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.NodeStyle", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Node", "Node")
                        .WithOne("NodeStyle")
                        .HasForeignKey("PrismaApi.Domain.Entities.NodeStyle", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Objective", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Project", "Project")
                        .WithMany("Objectives")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Option", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Decision", "Decision")
                        .WithMany("Options")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Decision");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Outcome", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Uncertainty", "Uncertainty")
                        .WithMany("Outcomes")
                        .HasForeignKey("UncertaintyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uncertainty");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Project", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.ProjectRole", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Project", "Project")
                        .WithMany("ProjectRoles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "User")
                        .WithMany("ProjectRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Strategy", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Project", "Project")
                        .WithMany("Strategies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Project");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.StrategyOption", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Option", "Option")
                        .WithMany("StrategyOptions")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrismaApi.Domain.Entities.Strategy", "Strategy")
                        .WithMany("StrategyOptions")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Uncertainty", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Issue", "Issue")
                        .WithOne("Uncertainty")
                        .HasForeignKey("PrismaApi.Domain.Entities.Uncertainty", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Utility", b =>
                {
                    b.HasOne("PrismaApi.Domain.Entities.Issue", "Issue")
                        .WithOne("Utility")
                        .HasForeignKey("PrismaApi.Domain.Entities.Utility", "IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Decision", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteProbability", b =>
                {
                    b.Navigation("ParentOptions");

                    b.Navigation("ParentOutcomes");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.DiscreteUtility", b =>
                {
                    b.Navigation("ParentOptions");

                    b.Navigation("ParentOutcomes");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Issue", b =>
                {
                    b.Navigation("Decision");

                    b.Navigation("Node");

                    b.Navigation("Uncertainty");

                    b.Navigation("Utility");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Node", b =>
                {
                    b.Navigation("HeadEdges");

                    b.Navigation("NodeStyle");

                    b.Navigation("TailEdges");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Option", b =>
                {
                    b.Navigation("StrategyOptions");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Project", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Issues");

                    b.Navigation("Nodes");

                    b.Navigation("Objectives");

                    b.Navigation("ProjectRoles");

                    b.Navigation("Strategies");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Strategy", b =>
                {
                    b.Navigation("StrategyOptions");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Uncertainty", b =>
                {
                    b.Navigation("DiscreteProbabilities");

                    b.Navigation("Outcomes");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.User", b =>
                {
                    b.Navigation("ProjectRoles");
                });

            modelBuilder.Entity("PrismaApi.Domain.Entities.Utility", b =>
                {
                    b.Navigation("DiscreteUtilities");
                });
#pragma warning restore 612, 618
        }
    }
}
