name: Pull Request
on:
    pull_request:
        branches:
            - main

permissions:
    contents: read
jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0.x"

            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.nuget/packages
                      ~/.dotnet/tools
                      ./PrismaApi/PrismaApi.Application/bin
                      ./PrismaApi/PrismaApi.Domain/bin
                      ./PrismaApi/PrismaApi.Infrastructure/bin
                      ./PrismaApi/PrismaApi.Api/bin
                  key: ${{ runner.os }}-dotnet-${{ hashFiles('**/PrismaApi*.csproj') }}

            - name: Restore NuGet packages
              run: dotnet restore PrismaApi/PrismaApi.sln

            - name: Build projects and their dependencies
              run: dotnet build --no-restore PrismaApi/PrismaApi.sln

    integration-tests:
        name: Integration tests
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-dotnet@v4

            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.nuget/packages
                      ~/.dotnet/tools
                      ./PrismaApi/PrismaApi.Application/bin
                      ./PrismaApi/PrismaApi.Domain/bin
                      ./PrismaApi/PrismaApi.Infrastructure/bin
                      ./PrismaApi/PrismaApi.Api/bin
                  key: ${{ runner.os }}-dotnet-${{ hashFiles('**/PrismaApi*.csproj') }}

            - name: Restore NuGet packages
              run: dotnet restore PrismaApi/PrismaApi.sln

            - name: Run tests
              run: |
                  dotnet build PrismaApi/PrismaApi.sln --configuration Release --no-restore
                  dotnet test PrismaApi/PrismaApi.Test/PrismaApi.Test.csproj --configuration Release --no-build --collect:"XPlat Code Coverage"

            - name: Publish test results
              uses: actions/upload-artifact@v4
              with:
                  name: TestResults
                  path: ./PrismaApi/PrismaApi.Test/TestResults

            - name: ReportGenerator
              uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
              with:
                  reports: ./PrismaApi/PrismaApi.Test/TestResults/**/*.cobertura.xml
                  targetdir: coveragereport
                  reporttypes: Html;MarkdownSummaryGithub

            - name: Upload coverage report artifact
              uses: actions/upload-artifact@v4
              with:
                  name: CoverageReport
                  path: coveragereport
